services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    restart: on-failure

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure
    depends_on:
      - zookeeper

  discoveryservice:
    container_name: discoveryservice
    build:
      context: ./discoveryservice
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: on-failure

  requestservice:
    container_name: requestservice
    build:
      context: ./requestservice
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - LOGSTASH_URL=logstash:5044
    ports:
      - "9001:9001"
    restart: on-failure
    depends_on:
      - discoveryservice
      - gatewayservice

  handlerservice:
    container_name: handlerservice
    build:
      context: ./handlerservice
      dockerfile: Dockerfile
    volumes:
      - E:/DEV/DEVOPS/devops-files-dev:/app/devops-files
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - LOGSTASH_URL=logstash:5044
    ports:
      - "9002:9002"
    restart: on-failure
    depends_on:
      - discoveryservice
      - gatewayservice

  gatewayservice:
    container_name: gatewayservice
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - LOGSTASH_URL=logstash:5044
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql
      - discoveryservice

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.1
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  db_data: